components:
  schemas:
    MenuItem:
      type: object
      additionalProperties: false
      properties:
        id:
          type: number
        name:
          type: string
        description:
          type: string
        price:
          type: number
        category:
          type: string
        isAvailable:
          type: boolean
    MenuItemRequestBody:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        category:
          type: string
        isAvailable:
          type: boolean
          